const auth = {
    AUTH_REQUEST_PENDING: "AUTH_REQUEST_PENDING",
    AUTH_REQUEST_FULFILLED: "AUTH_REQUEST_FULFILLED",
    SIGN_IN: "SIGN_IN",
    CHECK_AUTHORISED_USER: "CHECK_AUTHORISED_USER",
}

export default auth