export const LOAD_AUDIENCE_LIST = 'LOAD_AUDIENCE_LIST';
export const LOAD_AUDIENCE_COUNT = 'LOAD_AUDIENCE_COUNT';
export const LOAD_CURRENT_AUDIENCE = 'LOAD_CURRENT_AUDIENCE';
export const LOAD_DATA_PARTNERS = 'LOAD_DATA_PARTNERS';
export const DATA_PARTNERS_REQUEST_PENDING = 'DATA_PARTNERS_REQUEST_PENDING'
export const  DATA_PARTNERS_REQUEST_FULFILLED = 'DATA_PARTNERS_REQUEST_FULFILLED'
