export const AUTH_REQUEST_PENDING = 'AUTH_REQUEST_PENDING';
export const AUTH_REQUEST_FULFILLED = 'AUTH_REQUEST_FULFILLED';
export const AUTH_REQUEST_FULFILLED_ERROR = 'AUTH_REQUEST_FULFILLED_ERROR';

export const GENERATE_PUBLISHER_KEY = 'GENERATE_PUBLISHER_KEY';
export const GENERATE_ADVERTISER_KEY = 'GENERATE_ADVERTISER_KEY';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_AS = 'SIGN_IN_AS';
export const LOG_OUT = 'LOG_OUT';
export const SIGN_IN_VIA_TOKEN = 'SIGN_IN_VIA_TOKEN';
export const ACCEPT_AGREEMENT = 'ACCEPT_AGREEMENT';

export const CREATE_BILLING_DETAILS = 'CREATE_BILLING_DETAILS';

export const RESET_REDUX_STATE = 'RESET_REDUX_STATE';
