export const BILLING_REQUEST_PENDING = 'BILLING_REQUEST_PENDING';
export const BILLING_REQUEST_FULFILLED = 'BILLING_REQUEST_FULFILLED';

export const LOAD_BILLING = 'LOAD_BILLING';
export const LOAD_CURRENT_BILLING = 'LOAD_CURRENT_BILLING';
