export const BUDGETS_REQUEST_PENDING = 'BUDGETS_REQUEST_PENDING';
export const BUDGETS_REQUEST_FULFILLED = 'BUDGETS_REQUEST_FULFILLED';

export const CREATE_BUDGET = 'CREATE_BUDGET';
export const DELETE_BUDGET = 'DELETE_BUDGET';
export const LOAD_BUDGETS = 'LOAD_BUDGETS';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';

export const UNLIMITED = 'UNLIMITED';
