export const CAMPAIGNS_STATISTICS_REQUEST_PENDING = 'CAMPAIGNS_STATISTICS_REQUEST_PENDING';
export const CAMPAIGNS_STATISTICS_REQUEST_FULFILLED = 'CAMPAIGNS_STATISTICS_REQUEST_FULFILLED';

export const LOAD_CAMPAIGNS_STATISTICS = 'LOAD_CAMPAIGNS_STATISTICS';
export const UPDATE_CAMPAIGN_STATISTIC = 'UPDATE_CAMPAIGN_STATISTIC';
