export const COUNTRIES_REQUEST_PENDING = 'COUNTRIES_REQUEST_PENDING';
export const COUNTRIES_REQUEST_FULFILLED = 'COUNTRIES_REQUEST_FULFILLED';
export const STATES_REQUEST_PENDING = 'STATES_REQUEST_PENDING';
export const STATES_REQUEST_FULFILLED = 'STATES_REQUEST_FULFILLED';
export const CITIES_REQUEST_PENDING = 'CITIES_REQUEST_PENDING';
export const CITIES_REQUEST_FULFILLED = 'CITIES_REQUEST_FULFILLED';
export const LANGUAGES_REQUEST_PENDING = 'LANGUAGES_REQUEST_PENDING';
export const LANGUAGES_REQUEST_FULFILLED = 'LANGUAGES_REQUEST_FULFILLED';

export const LOAD_COUNTRIES = 'LOAD_COUNTRIES';
export const LOAD_CITIES = 'LOAD_CITIES';
export const LOAD_STATES = 'LOAD_STATES';
export const LOAD_LANGUAGES = 'LOAD_LANGUAGES';
