export const LOAD_DSP_INTEGRATIONS = 'LOAD_DSP_INTEGRATIONS';
export const DSP_INTEGRATIONS_REQUEST_PENDING = 'DSP_INTEGRATIONS_REQUEST_PENDING';
export const DSP_INTEGRATIONS_REQUEST_COMPLETED = 'DSP_INTEGRATIONS_REQUEST_COMPLETED';
export const LOAD_BANNER_RESOLUTIONS = 'LOAD_BANNER_RESOLUTIONS';
