export const FORGOT_PASSWORD_REQUEST_PENDING = 'FORGOT_PASSWORD_REQUEST_PENDING';
export const FORGOT_PASSWORD_REQUEST_FULFILLED = 'FORGOT_PASSWORD_REQUEST_FULFILLED';

export const SHOW_FORGOT_PASSWORD_SUCCESS_MESSAGE = 'SHOW_FORGOT_PASSWORD_SUCCESS_MESSAGE';
export const SHOW_UPDATE_PASSWORD_SUCCESS_MESSAGE = 'SHOW_UPDATE_PASSWORD_SUCCESS_MESSAGE';

export const RESET_FORGOT_PASSWORD_STATE = 'RESET_FORGOT_PASSWORD_STATE';
