export const NOTIFICATIONS_REQUEST_PENDING = 'NOTIFICATIONS_REQUEST_PENDING';
export const NOTIFICATIONS_REQUEST_FULFILLED = 'NOTIFICATIONS_REQUEST_FULFILLED';

export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';