export const PUBLISHERS_STATISTICS_REQUEST_PENDING = 'PUBLISHERS_STATISTICS_REQUEST_PENDING';
export const PUBLISHERS_STATISTICS_REQUEST_FULFILLED = 'PUBLISHERS_STATISTICS_REQUEST_FULFILLED';

export const LOAD_PUBLISHERS_STATISTICS = 'LOAD_PUBLISHERS_STATISTICS';
