export const WHITELIST = 'WHITELIST';
export const BLACKLIST = 'BLACKLIST';

export const LOW_PERFORMANCE = 'LOW_PERFORMANCE';
export const KPI_NOT_REACHED = 'KPI_NOT_REACHED';
export const LOW_RR = 'LOW_RR';
export const ZERO_PERFORMANCE = 'ZERO_PERFORMANCE';
export const CUSTOM = 'CUSTOM';

export const REQUEST_PENDING = 'REQUEST_PENDING';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const SUBID_WHITE_LIST_REQUEST_PENDING = 'SUBID_WHITE_LIST_REQUEST_PENDING';
export const SUBID_BLACK_LIST_REQUEST_PENDING = 'SUBID_BLACK_LIST_REQUEST_PENDING';

export const SUBID_WHITE_LIST_REQUEST_FULFILLED = 'SUBID_WHITE_LIST_REQUEST_FULFILLED';
export const SUBID_BLACK_LIST_REQUEST_FULFILLED = 'SUBID_BLACK_LIST_REQUEST_FULFILLED';

export const CREATE_SUBID_WHITE_LIST_ITEM = 'CREATE_SUBID_WHITE_LIST_ITEM';
export const CREATE_SUBID_BLACK_LIST_ITEM = 'CREATE_SUBID_BLACK_LIST_ITEM';

export const DELETE_SUBID_WHITE_LIST_ITEM = 'DELETE_SUBID_WHITE_LIST_ITEM';
export const DELETE_SUBID_BLACK_LIST_ITEM = 'DELETE_SUBID_BLACK_LIST_ITEM';

export const LOAD_SUBID_WHITE_LIST = 'LOAD_SUBID_WHITE_LIST';
export const LOAD_SUBID_BLACK_LIST = 'LOAD_SUBID_BLACK_LIST';
export const LOAD_LIMIT_COUNT_SUBID_BLACK_LIST = 'LOAD_LIMIT_COUNT_SUBID_BLACK_LIST';
