export const TOP_COUNTRIES_REQUEST_PENDING = 'TOP_COUNTRIES_REQUEST_PENDING';
export const TOP_COUNTRIES_REQUEST_FULFILLED = 'TOP_COUNTRIES_REQUEST_FULFILLED';
export const LOAD_TOP_COUNTRIES = 'LOAD_TOP_COUNTRIES';
