export const TOP_CAMPAIGNS_REQUEST_PENDING = 'TOP_CAMPAIGNS_REQUEST_PENDING';
export const TOP_CAMPAIGNS_REQUEST_FULFILLED = 'TOP_CAMPAIGNS_REQUEST_FULFILLED';
export const LOAD_TOP_CAMPAIGNS = 'LOAD_TOP_CAMPAIGNS';
