export const CAMPAIGN = 'CAMPAIGN';
export const PUBLISHER = 'PUBLISHER';

export const TOP_EARNINGS_REQUEST_PENDING = 'TOP_EARNINGS_REQUEST_PENDING';
export const TOP_EARNINGS_REQUEST_FULFILLED = 'TOP_EARNINGS_REQUEST_FULFILLED';

export const LOAD_TOP_EARNINGS = 'LOAD_TOP_EARNINGS';
