export const CHECK_SEND_EMAIL_TEST = 'CHECK_SEND_EMAIL_TEST';
export const HIGHLIGHT_CLICK_TEST = 'HIGHLIGHT_CLICK_TEST';
export const CHECK_CLICK_TEST = 'CHECK_CLICK_TEST';
export const HIGHLIGHT_INSTALL_TEST = 'HIGHLIGHT_INSTALL_TEST';
export const CHECK_INSTALL_TEST = 'CHECK_INSTALL_TEST';

export const EMAIL_REQUEST_PENDING = 'EMAIL_REQUEST_PENDING';
export const EMAIL_REQUEST_FULFILLED = 'EMAIL_REQUEST_FULFILLED';

export const SET_EMAIL_ERROR = 'SET_EMAIL_ERROR';
export const CLEAR_EMAIL_ERROR = 'CLEAR_EMAIL_ERROR';

export const RESET_TRACKING_STATE = 'RESET_TRACKING_STATE';
