export const USERS_REQUEST_PENDING = 'USERS_REQUEST_PENDING';
export const USERS_REQUEST_FULFILLED = 'USERS_REQUEST_FULFILLED';

export const LOAD_ADVERTISERS = 'LOAD_ADVERTISERS';
export const LOAD_PUBLISHERS = 'LOAD_PUBLISHERS';
export const LOAD_USERS = 'LOAD_USERS';

export const LOAD_ADVERTISER_DETAILS = 'LOAD_ADVERTISER_DETAILS';
export const LOAD_PUBLISHER_LIST_DROPDOWN = 'LOAD_PUBLISHER_LIST_DROPDOWN';
export const UPDATE_PUBLISHER = 'UPDATE_PUBLISHER';
export const UPDATE_USER = 'UPDATE_USER';

export const DELETE_ADVERTISER = 'DELETE_ADVERTISER';
export const DELETE_PUBLISHER = 'DELETE_PUBLISHER';

export const CREATE_USER = 'CREATE_USER';
export const UPDATE_PUBLISHER_STATUS = 'UPDATE_PUBLISHER_STATUS';
export const UPDATE_ADVERTISER_STATUS = 'UPDATE_ADVERTISER_STATUS';

export const ADVERTISER = 'ADVERTISER';
export const OWNER = 'OWNER';
export const ADMIN = 'ADMIN';
export const ACCOUNT_MANAGER = 'ACCOUNT_MANAGER';
export const PUBLISHER = 'PUBLISHER';

export const MEDIA_BUYING_TEAM = 'MEDIA_BUYING_TEAM';
export const AD_NETWORK = 'AD_NETWORK';
export const AFFILIATE_NETWORK = 'AFFILIATE_NETWORK';
export const AD_AGENCY = 'AD_AGENCY';
export const SSP = 'SSP';

export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const PENDING = 'PENDING';
export const REJECTED = 'REJECTED';
export const ACTIVE = 'ACTIVE';
export const REMOVED = 'REMOVED';
export const PAUSED = 'PAUSED';

export const FILTER_BY_NAME = 'FILTER_BY_NAME';

export const SET_MANAGERS = 'SET_MANAGERS';
export const SET_ADMINS = 'SET_ADMINS';
export const RESET_CURRENT_USER = 'RESET_CURRENT_USER';
export const SET_CURRENT_PUBLISHER = 'SET_CURRENT_PUBLISHER';
export const RESET_CURRENT_PUBLISHER = 'RESET_CURRENT_PUBLISHER';
export const SET_KEY_BY_ADMIN = 'SET_KEY_BY_ADMIN';
export const SET_API_KEY_TO_ADVERTISER_BY_ADMIN = 'SET_API_KEY_TO_ADVERTISER_BY_ADMIN';

export const RESET_CURRENT_ADVERTISER = 'RESET_CURRENT_ADVERTISER';
