const segmentsDigiseg = {
    a1: "Accommodation Type > Apartment",
    a2: "Accommodation Type > House / Semi detached",
    b1: "Savings > No Savings",
    b2: "Savings > Smaller Savings",
    b3: "Savings > Larger Savings",
    c1: "Lifecycle > Young single and couples",
    c2: "Lifecycle > Young",
    c3: "Lifecycle > Families with school children",
    c4: "Lifecycle > Older families matured couples",
    c5: "Lifecycle > Pensioners",
    d1: "Cars in the household > 0 Cars",
    d2: "Cars in the household > 1 Cars",
    d3: "Cars in the household > 2 or more cars",
    e1: "Children in the household > Households without children",
    e2: "Children in the household > Households with 1 children",
    e3: "Children in the household > Households with 2 or more children",
    f1: "Education > Basic",
    f2: "Education > Medium",
    f3: "Education > Higher",
    g1: "Neighborhood Type > Countryside",
    g2: "Neighborhood Type > Village",
    g3: "Neighborhood Type > Suburban",
    g4: "Neighborhood Type > City",
    h1: "Household Income > Lowest 20%",
    h2: "Household Income > Lowest 20-40%",
    h3: "Household Income > Middle 40-60%",
    h4: "Household Income > Highest 60-80%",
    h5: "Household Income > Top 20%",
    j1: "Home Ownership > Rent",
    j2: "Home Ownership > Own",
    k1: "Building Year > Before 1945",
    k2: "Building Year > 1945 - 1995",
    k3: "Building Year > From 1995 till today",
    l1: "Living Space M2 > Up to 80 m2",
    l2: "Living Space M2 > 80-119 m2",
    l3: "Living Space M2 > Above 120 m2",
    n1: "Tech-Level in Household > Low",
    n2: "Tech-Level in Household > Medium",
    n3: "Tech-Level in Household > High",

    ba1: "Business Audiences > Small Business with 0-10 employees",
    ba2: "Business Audiences > Medium Business with 11-50 employees",
    ba3: "Business Audiences > Larger Business with >50 employees",

    co0001: "Cars > Micro/city cars (A)",
    co0002: "Cars > Mini (B)",
    co0003: "Cars > Small mediumclass/compact C",
    co0004: "Cars > Large mediumclass D",
    co0005: "Cars > Large premium cars E",
    co0006: "Cars > Large luxury sedan F",
    co0007: "Cars > MPV/Minivans M",
    co0008: "Cars > SUV J",
    co0009: "Cars > EL/Hybrid",
    co0010: "Cars > Sport cars",
    co0011: "Cars > Car service/car parts",
    co0012: "Cars > Car tires",
    co0013: "Cars > Private leasing",
    co0014: "Banking/Financing > House Loan",
    co0015: "Banking/Financing > Car loan",
    co0016: "Banking/Financing > Consumer Loans",
    co0017: "Banking/Financing > Renovation",
    co0018: "Banking/Financing > Quick loans",
    co0019: "Banking/Financing > Mobile banking",
    co0020: "Banking/Financing > Investors"
}

module.exports = {
    segmentsDigiseg
}