export const eventTypes = {
  USER_LOGIN: 'User login',
  USER_LOGOUT: 'User logout',
  USER_REPORTS_EXPORT: 'Reports export',
  USER_PASSWORD_RECOVERY: 'User password recovery',
  CAMPAIGN_NEW: 'Campaign new',
  CAMPAIGN_EDIT: 'Campaign edit',
  CAMPAIGN_PAUSED: 'Campaign pause',
  CAMPAIGN_DELETE: 'Campaign delete',
  CAMPAIGN_ACTIVE: 'Campaign activation',
  ADVERTISER_NEW: 'Advertiser new',
  REGISTER_ADVERTISER :'Register Advertiser',
  ADVERTISER_EDIT: 'Advertiser edit',
  ADVERTISER_ACTIVE: 'Advertiser activation',
  ADVERTISER_PAUSED: 'Advertiser pause',
  ADVERTISER_DELETED: 'Advertiser delete',
  PUBLISHER_NEW: 'Publisher new',
  PUBLISHER_EDIT: 'Publisher edit',
  PUBLISHER_DELETED: 'Publisher delete',
  PUBLISHER_REJECTED: 'Publisher reject',
  PUBLISHER_PAUSED: 'Publisher pause',
  PUBLISHER_ACTIVE: 'Publisher activation',
  PUBLISHER_BANNED: 'Publisher ban',
  ADMIN_NEW: 'Admin new',
  ACCOUNT_MANAGER_NEW: 'Manager new',
  ACCOUNT_MANAGER_EDIT: 'Manager edit',
  ACCOUNT_MANAGER_REMOVED: 'Manager removed',
  ACCOUNT_MANAGER_ACTIVE: 'Manager activation',
  ACCOUNT_MANAGER_BANNED: 'Manager ban',
  ADMIN_EDIT: 'Admin edit',
  ADMIN_ACTIVE: 'Admin activation',
  ADMIN_BANNED: 'Admin ban',
  ADMIN_REMOVED: 'Admin removed',
  USER_EDIT: 'User edit',
  USER_DELETE: 'User delete',
  ADVERTISER_BALANCE_EDIT: 'Advertiser balance edit',
  PAYOUT_EDIT: 'Payout edit',
  PUBLISHER_POSTBACK_CHANGE: 'Publisher postback change',
  WHITELIST_PUBLISHER_FOR_CAMPAIGN: 'Whitelist publisher for campaign',
  NEW_SUBSCRIPTION:'Advertiser subscription'
};
