export const roles = {
  PUBLISHER: 'PUBLISHER',
  ADVERTISER: 'ADVERTISER',
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  ACCOUNT_MANAGER: 'ACCOUNT_MANAGER',
};

export const permissions = {
  DASHBOARD: 'DASHBOARD',
  CAMPAIGN: 'CAMPAIGN',
  ADVERTISERS: 'ADVERTISERS',
  PUBLISHERS: 'PUBLISHERS',
  LOGS: 'LOGS',
  SEE_PROFIT: 'SEE_PROFIT',
  ADD_ADMINS: 'ADD_ADMINS',
  DELETE_USERS: 'DELETE_USERS',
};

export const publisherTypes = {
  MEDIA_BUYING_TEAM: 'MEDIA_BUYING_TEAM',
  AD_NETWORK: 'AD_NETWORK',
  AFFILIATE_NETWORK: 'AFFILIATE_NETWORK',
  AD_AGENCY: 'AD_AGENCY',
  SSP: 'SSP',
};


export const statuses = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  BANNED: 'BANNED',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  REMOVED: 'REMOVED',
};
