export const CONNECTOR_COLUMN_DEFS = [
  {
    headerClass: "ag-grid-header-cell",
    headerCheckboxSelection: true,
    headerCheckboxSelectionFilteredOnly: true,
    checkboxSelection: true,
    minWidth: 95,
    width: 95,
    maxWidth: 95,
  },
  {
    headerName: "Name",
    field: "name",
    headerClass: "ag-grid-header-cell",
    minWidth: 55,
    cellRenderer: "nameRenderer",
    width: 300,
    maxWidth: 300,
    tooltipField: "name",
  },
  {
    headerName: "Category",
    field: "category",
    headerClass: "ag-grid-header-cell",
    minWidth: 150,
    maxWidth: 350,
    tooltipField: "category",
  },
  {
    headerName: "Type",
    field: "type",
    headerClass: "ag-grid-header-cell",
    cellRenderer: "typeRenderer",
    minWidth: 100,
    maxWidth: 350,
  },
  {
    headerName: "Description",
    field: "description",
    headerClass: "ag-grid-header-cell",
    minWidth: 200,
    maxWidth: 350,
    tooltipField: "description",
  },
  {
    headerName: "Label(s)",
    field: "tags",
    headerClass: "ag-grid-header-cell",
    cellRenderer: "tagRenderer",
    minWidth: 150,
    maxWidth: 350,
    tooltipField: "tags",
  },
  {
    headerName: "Group(s)",
    field: "groups",
    headerClass: "ag-grid-header-cell",
    minWidth: 120,
    maxWidth: 250,
    cellRenderer: "groupRenderer",
    tooltipField: "description",
  },
  {
    headerName: "Status",
    field: "enabled",
    cellRenderer: "statusRenderer",
    headerClass: "ag-grid-header-cell",
    minWidth: 80,
  },
  {
    headerName: "Timestamp",
    field: "timestamp",
    cellRenderer: "timeRenderer",
    headerClass: "ag-grid-header-cell",
    minWidth: 100,
    maxWidth: 490,
    tooltipField: "timestamp",
  },
  {
    headerName: "Action",
    cellRenderer: "renderEditor",
    width: 200,
  },
];
