version: "3.3"
services:

  tracardi-gui:
    # image: insights/ui:multi  
    build:
      context: $PWD
      dockerfile: Dockerfile
    environment:
      API_URL: http://tracardi-api:8686
    ports:
      - 3000:80


