export const columnsDailyTabPerformance = {
  OWNER: [
    {
      headerName: 'Date',
      field: 'day',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 50,
      maxWidth: 380,
      pinnedRowCellRenderer: ({value}) => value,
    },
    {
      headerName: 'Bids',
      field: 'bidTotal',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Impressions',
      field: 'impressionsCount',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Clicks',
      field: 'clicksCount',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Conversions', children: [
        {
          headerName: 'Total',
          field: 'conversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed', inWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Rejected',
          field: 'rejectedConversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedConversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customToFixed',
    },
    {
      headerName: 'CR (%)',
      field: 'cr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Revenue ($)',
      field: 'spentAdvertiser',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Payout ($)',
      field: 'ownerSpent',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Profit ($)',
      field: 'ownerEarnings',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
  ADMIN: [
    {
      headerName: 'Date',
      field: 'day',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 50,
      maxWidth: 380,
      pinnedRowCellRenderer: ({value}) => value,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Responses',
      field: 'responses',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Bid rate (%)',
      field: 'bidRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Impressions image',
      children: [
        {
          headerName: 'Total',
          field: 'impressionsImage',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedImpressionsImage',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentApprovedImage',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Impressions icon',
      children: [
        {
          headerName: 'Total',
          field: 'impressionsIcon',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedImpressionsIcon',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentApprovedIcon',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Fill rate (%)',
      field: 'fillRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Clicks',
      children: [
        {
          headerName: 'Total',
          field: 'clicks',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedClicks',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentApprovedClicks',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customToFixed',
    },
    {
      headerName: 'Bid floor ($)',
      field: 'bidFloor',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'eCPM ($)',
      field: 'eCPM',
      headerClass: 'eCPM',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Revenue ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Payout ($)',
      field: 'payout',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Profit ($)',
      field: 'profit',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
  ACCOUNT_MANAGER: [
    {
      headerName: 'Date',
      field: 'day',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 50,
      maxWidth: 380,
      pinnedRowCellRenderer: ({value}) => value,
    },
    {
      headerName: 'Impressions image',
      children: [
        {
          headerName: 'Total',
          field: 'impressionsImage',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedImpressionsImage',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentApprovedImage',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Impressions icon',
      children: [
        {
          headerName: 'Total',
          field: 'impressionsIcon',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedImpressionsIcon',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentApprovedIcon',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Clicks',
      children: [
        {
          headerName: 'Total',
          field: 'clicks',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedClicks',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentApprovedClicks',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Conversions', children: [
        {
          headerName: 'Total',
          field: 'conversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed', inWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Rejected',
          field: 'rejectedConversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedConversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customToFixed',
    },
    {
      headerName: 'CR (%)',
      field: 'cr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Revenue ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Payout ($)',
      field: 'payout',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Profit ($)',
      field: 'profit',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
  ADVERTISER: [
    {
      headerName: 'Date',
      field: 'day',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 160,
      maxWidth: 380,
      pinnedRowCellRenderer: ({value}) => value,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 160,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Responses',
      field: 'responses',
      headerClass: 'ag-grid-header-cell',
      minWidth: 160,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Fill rate (%)',
      field: 'fillRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 160,
      maxWidth: 380,
    },
    {
      headerName: 'Impressions',
      children: [
        {
          headerName: 'Total',
          field: 'impressionsImage',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedImpressionsImage',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentApprovedImage',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 160,
      maxWidth: 380,
    },
    {
      headerName: 'Clicks',
      field: 'clicks',
      headerClass: 'ag-grid-header-cell',
      minWidth: 160,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 160,
      maxWidth: 380,
      cellRenderer: 'customToFixed',
    },
    {
      headerName: 'Spend ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 160,
      maxWidth: 380,
    },
  ],
  PUBLISHER: [
    {
      headerName: 'Date',
      field: 'day',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 50,
      maxWidth: 380,
      pinnedRowCellRenderer: ({value}) => value,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Responses',
      field: 'responses',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Fill rate (%)',
      field: 'fillRate',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Impressions',
      field: 'impressions',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Clicks',
      field: 'clicks',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customToFixed',
    },
    {
      headerName: 'Revenue ($)',
      field: 'payout',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
};
