export const columnsErrorsPublishersTabPerformance = {
  ADMIN: [
    {
      headerName: 'Publisher',
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 480,
    },
    {
      headerName: 'Status',
      field: 'status',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 480,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: 'Blacklisted',
      field: 'blacklisted',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: '%',
      field: 'percentBlacklisted',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Errors',
      field: 'errors',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: '%',
      field: 'percentErrors',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Forbidden',
      field: 'forbidden',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: '%',
      field: 'percentForbidden',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Bad Requests', children: [
        {
          headerName: 'Auction Type',
          field: 'auctionType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentAuctionType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Inventory Type',
          field: 'inventoryType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentInventoryType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Parse',
          field: 'parse',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentParse',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Ad Type',
          field: 'adType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentAdType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Tmax',
          field: 'tmax',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentTmax',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Geo',
          field: 'geo',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentGeo',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'IP',
          field: 'ip',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentIp',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Geo Match',
          field: 'geoMatch',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentGeoMatch',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'OS',
          field: 'os',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentOs',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Bid Floor',
          field: 'bidfloor',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentBidfloor',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Server Errors',
      field: 'serverErrors',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: '%',
      field: 'percentServerErrors',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
  ACCOUNT_MANAGER: [
    {
      headerName: 'Publisher',
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 480,
    },
    {
      headerName: 'Status',
      field: 'status',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 480,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: 'Blacklisted',
      field: 'blacklisted',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: '%',
      field: 'percentBlacklisted',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Errors',
      field: 'errors',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: '%',
      field: 'percentErrors',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Forbidden',
      field: 'forbidden',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: '%',
      field: 'percentForbidden',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Bad Requests', children: [
        {
          headerName: 'Auction Type',
          field: 'auctionType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentAuctionType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Inventory Type',
          field: 'inventoryType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentInventoryType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Parse',
          field: 'parse',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentParse',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Ad Type',
          field: 'adType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentAdType',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Tmax',
          field: 'tmax',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentTmax',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Geo',
          field: 'geo',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentGeo',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'IP',
          field: 'ip',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentIp',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Geo Match',
          field: 'geoMatch',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentGeoMatch',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'OS',
          field: 'os',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentOs',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Bid Floor',
          field: 'bidfloor',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'percentBidfloor',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Server Errors',
      field: 'serverErrors',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'numberCellRenderer',
    },
    {
      headerName: '%',
      field: 'percentServerErrors',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
};
