export const columnsPublishersTabPerformance = {
  ADMIN: [
    {
      headerName: 'Publisher',
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Responses',
      field: 'responses',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    // {
    //   headerName: 'Avg tmax',
    //   field: 'avgTmax',
    //   headerClass: 'ag-grid-header-cell',
    //   minWidth: 50,
    //   maxWidth: 380,
    //   cellRenderer: 'customNumberFormat',
    // },
    {
      headerName: 'Bid rate (%)',
      field: 'bidRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Impressions', children: [
        {
          headerName: 'Total',
          field: 'impressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedImpressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'perApprovedImpressions',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Fill rate (%)',
      field: 'fillRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Clicks', children: [
        {
          headerName: 'Total',
          field: 'clicks',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedClicks',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'perApprovedClicks',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customToFixed',
    },
    {
      headerName: 'Bid floor ($)',
      field: 'bidFloor',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'eCPM ($)',
      field: 'eCPM',
      headerClass: 'eCPM',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Revenue ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Payout', children: [
        {
          headerName: 'Total',
          field: 'payout',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'amountCellRenderer',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedPayout',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'amountCellRenderer',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'perApprovedPayout',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Profit ($)',
      field: 'profit',
      headerClass: 'ag-grid-header-cell',
      width: 100,
      minWidth: 90,
      maxWidth: 250,
    },
  ],
  ACCOUNT_MANAGER: [
    {
      headerName: 'Id',
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 350,
    },
    {
      headerName: 'Publisher',
      field: 'publisherId',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'publisherNameCellRenderer',
      pinnedRowCellRenderer: ({value}) => value,
    },
    {
      headerName: 'Impressions',
      field: 'impressionsCount',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Clicks',
      field: 'clicksCount',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Conversions', children: [
        {
          headerName: 'Total',
          field: 'conversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Rejected',
          field: '0',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: '0',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customToFixed',
    },
    {
      headerName: 'CR (%)',
      field: 'cr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Revenue ($)',
      field: 'spentAdvertiser',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
  ADVERTISER: [
    {
      headerName: 'Id',
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 350,
    },
    {
      headerName: 'Publisher',
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Responses',
      field: 'responses',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Fill rate (%)',
      field: 'fillRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Impressions',
      field: 'impressions',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Clicks',
      field: 'clicks',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customToFixed',
    },
    {
      headerName: 'Spend ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
  PUBLISHER: [
    {
      headerName: 'Id',
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 350,
    },
    {
      headerName: 'Publisher',
      field: 'publisherId',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'publisherCellRenderer',
      pinnedRowCellRenderer: ({value}) => value,
    },
    {
      headerName: 'Impressions',
      field: 'impressionsCount',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Clicks',
      field: 'clicksCount',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Conversions', children: [
        {
          headerName: 'Total',
          field: 'conversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Rejected',
          field: 'rejectedConversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedConversionsCount',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customToFixed',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customToFixed',
    },
    {
      headerName: 'CR (%)',
      field: 'cr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Profit ($)',
      field: 'ownerSpent',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
};
