export const columnsPublishersNoMatchCampaignTab = {
  ADMIN: [
    {
      headerName: 'Publisher',
      field: 'publisher',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 480,
    },
    {
      headerName: 'Campaign',
      field: 'campaign',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 480,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Blacklisted',
      field: 'blacklisted',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentBlacklisted',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'No Match',
      field: 'totalNoMatch',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentNoMatch',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'bid',
      field: 'bidFloor',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentBidFloor',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Inventory Type',
      field: 'trafficType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentTrafficType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Geo',
      field: 'geos',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentGeo',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Category',
      field: 'category',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentCategory',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Device Type',
      field: 'deviceType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentDeviceType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Platform',
      field: 'platform',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentPlatform',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },

    {
      headerName: 'Min OS',
      field: 'minOS',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentMinOS',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Max OS',
      field: 'maxOS',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentMaxOS',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Size',
      field: 'sizes',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentSize',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Required Params',
      field: 'requiredParams',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: '%',
      field: 'percentRequiredParams',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Connection Type',
      field: 'connectionType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentConnectionType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Carrier',
      field: 'carrier',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentCarrier',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Browser',
      field: 'browser',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentBrowser',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Language',
      field: 'language',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentLanguage',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Age',
      field: 'age',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentAge',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Gender',
      field: 'gender',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentGender',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
  ACCOUNT_MANAGER: [
    {
      headerName: 'Publisher',
      field: 'publisher',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 480,
    },
    {
      headerName: 'Campaign',
      field: 'campaign',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 480,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Blacklisted',
      field: 'blacklisted',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentBlacklisted',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'No Match',
      field: 'totalNoMatch',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentNoMatch',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'bid',
      field: 'bidFloor',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentBidFloor',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Inventory Type',
      field: 'trafficType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentTrafficType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Geo',
      field: 'geo',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentGeo',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Category',
      field: 'category',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentCategory',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Device Type',
      field: 'deviceType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentDeviceType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Platform',
      field: 'platform',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentPlatform',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },

    {
      headerName: 'Min OS',
      field: 'minOS',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentMinOS',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Max OS',
      field: 'maxOS',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentMaxOS',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Size',
      field: 'size',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentSize',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Required Params',
      field: 'requiredParams',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: '%',
      field: 'percentRequiredParams',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Connection Type',
      field: 'connectionType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentConnectionType',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Carrier',
      field: 'carrier',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentCarrier',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Browser',
      field: 'browser',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentBrowser',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Language',
      field: 'language',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentLanguage',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Age',
      field: 'age',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentAge',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Gender',
      field: 'gender',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: '%',
      field: 'percentGender',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
};
