export const columnsSubIdsTabPerformance = {
  ADMIN: [
    {
      headerName: 'Id',
      field: 'subidLabel',
      headerClass: 'ag-grid-header-cell',
      minWidth: 25,
      maxWidth: 150,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Responses',
      field: 'responses',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Fill rate (%)',
      field: 'fillRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Impressions', children: [
        {
          headerName: 'Total',
          field: 'impressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedImpressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'perApprovedImpressions',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Invalid Impressions', children: [
        {
          headerName: 'Total',
          field: 'rejectedImpressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'perRejectedImpressions',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Clicks',
      field: 'clicks',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      cellRenderer: 'customToFixed',
      maxWidth: 380,
    },
    {
      headerName: 'eCPM ($)',
      field: 'eCPM',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      cellRenderer: 'customToFixed',
      maxWidth: 380,
    },
    {
      headerName: 'Revenue ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'profitCellRenderer',
      width: 100,
      minWidth: 90,
      maxWidth: 250,
    },
    {
      headerName: 'Payout ($)',
      field: 'payout',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'profitCellRenderer',
      width: 100,
      minWidth: 90,
      maxWidth: 250,
    },
    {
      headerName: 'Profit ($)',
      field: 'profit',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'profitCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
  ],
  ADVERTISER: [
    {
      headerName: 'Id',
      field: 'subidLabel',
      headerClass: 'ag-grid-header-cell',
      minWidth: 25,
      maxWidth: 150,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Responses',
      field: 'responses',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Fill rate (%)',
      field: 'fillRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Impressions', children: [
        {
          headerName: 'Total',
          field: 'impressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedImpressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'perApprovedImpressions',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Invalid Impressions', children: [
        {
          headerName: 'Total',
          field: 'rejectedImpressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'perRejectedImpressions',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Clicks',
      field: 'clicks',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      cellRenderer: 'customToFixed',
      maxWidth: 380,
    },
    {
      headerName: 'eCPM ($)',
      field: 'eCPM',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      cellRenderer: 'customToFixed',
      maxWidth: 380,
    },
    {
      headerName: 'Spend ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'profitCellRenderer',
      width: 100,
      minWidth: 90,
      maxWidth: 250,
    },
  ],
  ACCOUNT_MANAGER: [
    {
      headerName: 'Date',
      field: 'createdAt',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'extendedDateCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Id',
      field: 'id',
      cellRenderer: 'conversionIdRendererAdmin',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 350,
    },
    {
      headerName: 'Campaign',
      field: 'campaignName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Advertiser',
      field: 'advertiserId',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'advertiserCellRenderer',
      minWidth: 50,
      maxWidth: 380,
      pinnedRowCellRenderer: ({value}) => value,
    },
    {
      headerName: 'Publisher',
      field: 'publisherId',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'publisherCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'OS',
      field: 'platform',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 100,
    },
    {
      headerName: 'Device',
      field: 'device',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Geo',
      field: 'ip',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'countryCellRenderer', tooltip: (params) => params.data.countryCode,
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Bid floor ($)',
      field: 'bidFloor',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'profitCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Status',
      field: 'status',
      headerClass: 'ag-grid-header-cell', cellStyle: {textTransform: 'uppercase',
      },
      cellRenderer: 'conversionStatusCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    /*    {
      headerName: 'Revenue ($)',
      field: 'payoutAdv',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Payout ($)',
      field: 'payoutPub',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Profit ($)',
      field: 'ownerEarnings',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      minWidth: 50,
      maxWidth: 380,
    },*/
  ],
  PUBLISHER: [
    {
      headerName: 'Id',
      field: 'subidLabel',
      headerClass: 'ag-grid-header-cell',
      minWidth: 25,
      maxWidth: 150,
    },
    {
      headerName: 'Requests',
      field: 'requests',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Responses',
      field: 'responses',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Fill rate (%)',
      field: 'fillRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Impressions', children: [
        {
          headerName: 'Total',
          field: 'impressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: 'Approved',
          field: 'approvedImpressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'perApprovedImpressions',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Invalid Impressions', children: [
        {
          headerName: 'Total',
          field: 'rejectedImpressions',
          headerClass: 'ag-grid-header-cell',
          cellRenderer: 'customNumberFormat',
          minWidth: 50,
          maxWidth: 380,
        },
        {
          headerName: '%',
          field: 'perRejectedImpressions',
          headerClass: 'ag-grid-header-cell',
          minWidth: 50,
          maxWidth: 380,
        },
      ],
    },
    {
      headerName: 'Win rate (%)',
      field: 'winRate',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 50,
      maxWidth: 380,
    },
    {
      headerName: 'Clicks',
      field: 'clicks',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 380,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      cellRenderer: 'customToFixed',
      maxWidth: 380,
    },
    {
      headerName: 'eCPM ($)',
      field: 'eCPM',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      cellRenderer: 'customToFixed',
      maxWidth: 380,
    },
    {
      headerName: 'Revenue ($)',
      field: 'payout',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'profitCellRenderer',
      width: 100,
      minWidth: 90,
      maxWidth: 250,
    },
  ],
};
