module.exports = {
  wlid: process.env.WLID || 1000,
  isProduction: process.env.NODE_ENV === 'PRODUCTION',
  db: {
    username: process.env.DB_USERNAME || 'postgres',
    password: process.env.DB_PASSWORD || 'postgres',
    database: process.env.DB_NAME || 'dsp',
    host: process.env.DB_HOSTNAME || '172.17.0.5',
    dialect: 'postgres',
    logging: process.env.NODE_ENV === 'DEVELOP',
    pool: {
      max: 30,
      min: 0,
      acquire: 60000,
      idle: 5000
    }
  },
  JWT_SECRET: process.env.JWT_SECRET || 's1F5EvRCgMwQlZe56',
  JWT_INTEGRATIONS_SECRET: process.env.JWT_INTEGRATIONS_SECRET || 'bb5dca31d4608d1654',
  AES_SECRET: process.env.AES_SECRET || '6kV1ZO88sswjKa8HCLVz2xJdinl7UXzy',
  mongoDB: {
    host: process.env.MONGO_DB_HOST || '172.17.0.3',
    user: process.env.MONGO_DB_USER || 'user',
    password: process.env.MONGO_DB_PASSWORD || '1',
    dbName: `dsp-logs-${process.env.WLID}`,
  },
  redisCreds: {
    host: process.env.REDIS_HOST || '172.17.0.4',
    port: process.env.REDIS_PORT || '6379',
    password: process.env.REDIS_PASSWORD || '1',
  },
  redisCreds2: {
    host: process.env.REDIS_HOST2 || '127.0.0.1',
    port: process.env.REDIS_PORT2 || '6379',
    password: process.env.REDIS_PASSWORD2 || '1',
  },
  redisTraffCreds: {
    host: process.env.REDIS_TRAFF_HOST || '127.0.0.1',
    port: process.env.REDIS_TRAFF_PORT || '6379',
    password: process.env.REDIS_TRAFF_PASSWORD || '1',
  },
  defaultAdmin: {
    email: process.env.DEFAULT_ADMIN_EMAIL,
    name: process.env.DEFAULT_ADMIN_NAME,
    pass: process.env.DEFAULT_ADMIN_PASS,
  },
  defaultManager: {
    email: process.env.DEFAULT_MANAGER_EMAIL,
    name: process.env.DEFAULT_MANAGER_NAME,
    pass: process.env.DEFAULT_MANAGER_PASS,
  },
  defaultPayout: 75,
  email: {
    host: process.env.EMAIL_HOST || 'smtp.gmail.com',
    port: process.env.EMAIL_PORT || '465',
    isSecure: process.env.EMAIL_IS_SECURE || true,
    authUser: process.env.EMAIL_AUTH_USER || 'test@gmail.com',
    authPassword: process.env.EMAIL_AUTH_PASSWORD || 'test-password',
    sender: process.env.EMAIL_OPTIONS_SENDER || 'dsp.test@gmail.com',
    rejectUnauthorized: process.env.EMAIL_REJECT_UNAUTHORIZED || false,
    adminEmail: process.env.EMAIL_ADMIN || 'admin.test@mail.com',
  },
  creatives: {
    host: process.env.CREATIVES_HOST || 'http://127.0.0.1:3000',
  },
  console:{
    host:process.env.DIY_HOST || 'http://127.0.0.1:3000'
  },
  appHost: process.env.APP_HOST || 'http://127.0.0.1:3000',
  uiHost: process.env.UI_HOST || 'http://127.0.0.1:3033',
  domainName: process.env.APP_HOST || '127.0.0.1:3000',
  MINIMUM_BALANCE: 10,
  SSP_PAYOUT: 75,
  clickhouse: {
    CH_HOST: process.env.CH_CLUSTER_HOST  || '172.17.0.5',
    CH_PORT: process.env.CH_CLUSTER_PORT || '8123',
    CH_USER: process.env.CH_CLUSTER_USER || '',
    CH_PASSWORD: process.env.CH_CLUSTER_PASS || '',
    distributed_impressions:'distributed_impressions_local_v3',
    distributed_clicks:'distributed_clicks_local_v3',
    versionTable: 'local_v3',
    versionWinsTable: 'local_v1',
    VERSION_BIDREQUEST_TABLE: 'local_v5',
    COUNTER_VERSIONS: process.env.COUNTER_VERSIONS || 'counter_main_v5',
    VERSION_PUBLISHER_QPM_TABLE: process.env.VERSION_PUBLISHER_QPM_TABLE || 'local_v1',
    PUBLISHER_SUB_ID_STATS_COUNTER_TABLE: process.env.PUBLISHER_SUB_ID_STATS_COUNTER_TABLE || 'bidrequests_counter_sites_v5',

    bidReqCounterMain: process.env.BID_REQ_COUNTER_MAIN || 'counter_main_v5',
    bidReqCounterTmax: process.env.BID_REQ_COUNTER_TMAX || 'counter_tmax_v5',
    bidReqCounterSubId: process.env.BID_REQ_COUNTER_SUB_ID || 'counter_subid_v5',
    bidReqCounterSites: process.env.BID_REQ_COUNTER_SITES || 'counter_sites_v5',
    bidReqCounterApps: process.env.BID_REQ_COUNTER_APPS || 'counter_apps_v5',
    bidReqCounterCampaign: process.env.BID_REQ_COUNTER_CAMPAIGN || 'counter_campaign_v5',
    bidReqCounterCreative: process.env.BID_REQ_COUNTER_CREATIVE || 'counter_cr_v5',
    impressions: process.env.IMPRESSIONS || 'local_v2',
    clicks: process.env.CLICKS || 'local_v2',
  },
  clickhouseCluster: {
    host: process.env.CH_CLUSTER_HOST || '172.17.0.5',
    port: process.env.CH_CLUSTER_PORT || '8123',
    user: process.env.CH_CLUSTER_USER || '',
    password: process.env.CH_CLUSTER_PASS || '',
    AUDIENCE_USERS: 'users_local_v1',
    IP_USERS:'ip_local_v1',
    versionTable: 'local_v2',
    versionWinsTable: 'local_v1',
    VERSION_BIDREQUEST_TABLE: 'local_v5',
    COUNTER_VERSIONS: process.env.COUNTER_VERSIONS || 'counter_main_v5',
    VERSION_PUBLISHER_QPM_TABLE: process.env.VERSION_PUBLISHER_QPM_TABLE || 'local_v1',
    PUBLISHER_SUB_ID_STATS_COUNTER_TABLE: process.env.PUBLISHER_SUB_ID_STATS_COUNTER_TABLE || 'bidrequests_counter_sites_v5',

    BIDREQ_COUNTER_DAILY: 'distributed_bidrequests_counter_daily_v6',
    BIDREQ_COUNTER_DAILY_CAMPAIGN: 'distributed_bidrequests_counter_daily_campaigns_v6',
    BIDREQ_COUNTER_DAILY_ADVERTISER: 'distributed_bidrequests_counter_daily_advertisers_v6',
    BIDREQ_COUNTER_GEO: 'distributed_bidrequests_counter_geo_v6',
    BIDREQ_COUNTER_GEO_ADVERTISER: 'distributed_bidrequests_counter_geo_advertisers_v6',
    BIDREQ_COUNTER_GEO_CAMPAIGN: 'distributed_bidrequests_counter_geo_campaigns_v6',
    BIDREQ_COUNTER_SUBID: 'distributed_bidrequests_counter_subid_v6',
    BIDREQ_COUNTER_SIZE_CRID_CAMPAIGN: 'distributed_bidrequests_counter_sizes_crids_campaigns_v6',
    BIDREQ_COUNTER_APP: 'distributed_bidrequests_counter_apps_campaigns_v6',
    BIDREQ_COUNTER_SITE: 'distributed_bidrequests_counter_sites_campaigns_v6',
    BIDREQ_COUNTER_SUBID_ADVERTISER: 'distributed_bidrequests_counter_subid_advertisers_v6',
    BIDREQ_COUNTER_SUBID_CAMPAIGN: 'distributed_bidrequests_counter_subid_campaigns_v6',
    BIDREQ_COUNTER_OS_CAMPAIGN: 'distributed_bidrequests_counter_os_campaigns_v6',
    BIDREQ_COUNTER_APP_ADVERTISER: 'distributed_bidrequests_counter_apps_advertisers_v6',
    BIDREQ_COUNTER_APP_CAMPAIGN: 'distributed_bidrequests_counter_apps_campaigns_v6',
    BIDREQ_COUNTER_SITE_ADVERTISER: 'distributed_bidrequests_counter_sites_advertisers_v6',
    BIDREQ_COUNTER_SITE_CAMPAIGN: 'distributed_bidrequests_counter_sites_campaigns_v6',
    BIDRES_COUNTER_DAILY: 'distributed_bidresponses_counter_daily_v3',
    BIDRES_COUNTER_DAILY_CAMPAIGN: 'distributed_bidresponses_counter_daily_campaigns_v3',
    BIDRES_COUNTER_HOUR_CAMPAIGN: 'distributed_bidresponses_counter_hour_campaigns_v3',
    BIDRES_COUNTER_CAMPAIGN: 'distributed_bidresponses_counter_campaigns_v3',
    BIDRES_COUNTER_GEO: 'distributed_bidresponses_counter_geo_v3',
    BIDRES_COUNTER_GEO_ADVERTISER: 'distributed_bidresponses_counter_geo_advertisers_v3',
    BIDRES_COUNTER_GEO_CAMPAIGN: 'distributed_bidresponses_counter_geo_campaigns_v3',
    BIDRES_COUNTER_SUBID: 'distributed_bidresponses_counter_subid_v3',
    BIDRES_COUNTER_SIZE_CRID: 'distributed_bidresponses_counter_sizes_crids_v3',
    BIDRES_COUNTER_APP: 'distributed_bidresponses_counter_apps_v3',
    BIDRES_COUNTER_SITE: 'distributed_bidresponses_counter_sites_v3',
    BIDRES_COUNTER_OS_CAMPAIGN: 'distributed_bidresponses_counter_os_campaigns_v3',
    BIDRES_COUNTER_SUBID_ADVERTISER: 'distributed_bidresponses_counter_subid_advertisers_v3',
    BIDRES_COUNTER_SUBID_CAMPAIGN: 'distributed_bidresponses_counter_subid_campaigns_v3',
    BIDRES_COUNTER_APP_ADVERTISER: 'distributed_bidresponses_counter_apps_advertisers_v3',
    BIDRES_COUNTER_APP_CAMPAIGN: 'distributed_bidresponses_counter_apps_campaigns_v3',
    BIDRES_COUNTER_SITE_ADVERTISER: 'distributed_bidresponses_counter_sites_advertisers_v3',
    BIDRES_COUNTER_SITE_CAMPAIGN: 'distributed_bidresponses_counter_sites_campaigns_v3',
    BIDRES_COUNTER_DAILY_ADVERTISER: 'distributed_bidresponses_counter_daily_advertisers_v3',
    IMP_COUNTER_DAILY: 'distributed_impressions_counter_campaigns_v3',
    IMP_COUNTER_GEO: 'distributed_impressions_counter_geo_v3',
    IMP_COUNTER_SUBID: 'distributed_impressions_counter_subid_v3',
    IMP_COUNTER_OS: 'distributed_impressions_counter_os_v3',
    IMP_COUNTER_SIZE_CRID: 'distributed_impressions_counter_sizes_crids_v3',
    IMP_COUNTER_APP: 'distributed_impressions_counter_apps_v3',
    IMP_COUNTER_SITE: 'distributed_impressions_counter_sites_v3',
    IMP_COUNTER_CAMPAIGN: 'distributed_impressions_counter_campaigns_v3',
    IMP_COUNTER_DAILY_CAMPAIGN: 'distributed_impressions_counter_campaigns_v3',
    IMP_COUNTER_HOUR_CAMPAIGN: 'distributed_impressions_counter_hour_campaigns_v3',
    CLICK_COUNTER_DAILY: 'distributed_clicks_counter_campaigns_v3',
    CLICK_COUNTER_GEO: 'distributed_clicks_counter_geo_v3',
    CLICK_COUNTER_OS: 'distributed_clicks_counter_os_v3',
    CLICK_COUNTER_SUBID: 'distributed_clicks_counter_subid_v3',
    CLICK_COUNTER_SIZE_CRID: 'distributed_clicks_counter_sizes_crids_v3',
    CLICK_COUNTER_APP: 'distributed_clicks_counter_apps_v3',
    CLICK_COUNTER_SITE: 'distributed_clicks_counter_sites_v3',
    CLICK_COUNTER_CAMPAIGN: 'distributed_clicks_counter_campaigns_v3',
    CLICK_COUNTER_DAILY_CAMPAIGN: 'distributed_clicks_counter_campaigns_v3',

    BIDREQ_COUNTER_HOUR: 'distributed_bidrequests_counter_hour_v6',
    BIDREQ_COUNTER_HOUR_CAMPAIGN: 'distributed_bidrequests_counter_hour_campaigns_v6',
    BIDREQ_COUNTER_HOUR_ADVERTISER: 'distributed_bidrequests_counter_hour_advertisers_v6',
    BIDRES_COUNTER_HOUR: 'distributed_bidresponses_counter_hour_v3',
    BIDRES_COUNTER_HOUR_ADVERTISER: 'distributed_bidresponses_counter_hour_advertisers_v3',
    IMP_COUNTER_HOUR: 'distributed_impressions_counter_hour_v3',
    CLICK_COUNTER_HOUR: 'distributed_clicks_counter_hour_v3',
    CLICK_COUNTER_HOUR_CAMPAIGN: 'distributed_clicks_counter_hour_campaigns_v3',
    PUB_ERROR_COUNTER: 'distributed_publisher_errors_counter_v2',
    CAMPAIGN_NOMATCH_COUNTER: 'distributed_nomatch_local_v2',

    bidReqCounterTmax: process.env.BID_REQ_COUNTER_TMAX || 'counter_tmax_v5',
    bidReqCounterSubId: process.env.BID_REQ_COUNTER_SUB_ID || 'counter_subid_v5',
    bidReqCounterSites: process.env.BID_REQ_COUNTER_SITES || 'counter_sites_v5',
    bidReqCounterApps: process.env.BID_REQ_COUNTER_APPS || 'counter_apps_v5',
    bidReqCounterCampaign: process.env.BID_REQ_COUNTER_CAMPAIGN || 'counter_campaign_v5',
    bidReqCounterCreative: process.env.BID_REQ_COUNTER_CREATIVE || 'counter_cr_v5',
    impressions: process.env.IMPRESSIONS || 'local_v3',
    clicks: process.env.CLICKS || 'local_v3',
  },
  handler: {
    impressionDomain: process.env.IMPRESSION_URL || '',
    clickDomain: process.env.CLICK_URL || '',
  },
  red: '\x1b[31m',
  accessToCDN: [1000],
  geoEdgeAccessToken: process.env.GEOEDGE_ACCESS_TOKEN,
  rollbarAccessToken: process.env.ROLLBAR_ACCESS_TOKEN,
  liveramp:{
    apiURI: "https://api.liveramp.com/data-marketplace",
    accountID: process.env.LIVERAMP_ACCOUNT_ID,
    clientID: process.env.LIVERAMP_CLIENT_ID || 'liveramp-api' ,
    ownerOrg: process.env.LIVERAMP_OWNER_ORG,
    secretKey: process.env.LIVERAMP_SECRET_KEY,
    tokenURI: "https://serviceaccounts.liveramp.com/authn/v1/oauth2/token",
    accountType: "serviceAccount/v2",
    destinationId: process.env.LIVERAMP_RDX_DESTINATION_ID||"ddbeff8d-e778-4ea1-866f-5192f692a956",
  },
  secret_key: process.env.SESSION_SECRET || 'ReBiD-TeSt@12345',
  keyCloak:{
    realm: process.env.REALM,
    auth_server_url: process.env.AUTH_SERVER_URL
  },
  console_api_url: process.env.CONSOLE_API_URL || 'https://dev-console.rebid.co',
  console_payment_url: process.env.CONSOLE_PAYMENT_URL || 'https://dev-console.rebid.co/payment',
  minSpend: process.env.MIN_SPEND || 30
};