import localization from '../../../localization';

export const ADVERTISERS_COLUMN_DEFS = {
  ADMIN: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 95,
      width: 95,
      maxWidth: 95,
    },
    {
      headerName: localization.advertisers.table.id,
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 55,
      width: 85,
      maxWidth: 100,
    },
    {
      headerName: localization.advertisers.table.name,
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'advPubRenderer',
      minWidth: 100,
      maxWidth: 350,
      tooltipField: 'name',
    },
    {
      headerName: localization.advertisers.table.companyName,
      field: 'companyName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 100,
      maxWidth: 320,
      tooltipField: 'companyName',
    },
    {
      headerName: localization.advertisers.table.balance,
      field: 'balance',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'balanceRenderer',
      minWidth: 100,
      maxWidth: 350,
    },
    {
      headerName: 'Spend ($)',
      field: 'spend',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 100,
      maxWidth: 350,
    },
    {
      headerName: localization.advertisers.table.campaignsCount,
      field: 'campaignsCount',
      headerClass: 'ag-grid-header-cell',
      minWidth: 100,
      maxWidth: 390,
      tooltipField: 'campaignsCount',
    },
    {
      headerName: localization.advertisers.table.manager,
      field: 'managerName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 100,
      maxWidth: 490,
      tooltipField: 'managerName',
    },
    // {headerName: localization.advertisers.table.country, field: 'country', headerClass: 'ag-grid-header-cell', cellRenderer: 'countryRenderer', minWidth: 80, maxWidth: 360, tooltipField: 'country'},
    {
      headerName: localization.advertisers.table.email,
      field: 'email',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'advPubMailRenderer',
      minWidth: 100,
      maxWidth: 650,
      tooltipField: 'email',
    },
    {
      headerName: localization.advertisers.table.status,
      field: 'status',
      cellRenderer: 'statusRenderer',
      headerClass: 'ag-grid-header-cell',
      minWidth: 80,
    },
    {
      headerName: localization.advertisers.table.registered,
      field: 'createdAt',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 150,
      width: 160,
      maxWidth: 350,
      tooltipField: 'createdAt',
    },
    // {headerName: localization.advertisers.table.skype, field: 'skype', headerClass: 'ag-grid-header-cell', minWidth: 80, maxWidth: 270, tooltipField: 'skype'},
    {
      headerName: 'Action',
      cellRenderer: 'renderEditor',
      width: 200,
    },
  ],
  ACCOUNT_MANAGER: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 56,
      width: 56,
      maxWidth: 95,
    },
    {
      headerName: localization.advertisers.table.id,
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 55,
      width: 85,
      maxWidth: 100,
    },
    {
      headerName: localization.advertisers.table.name,
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'advPubRenderer',
      minWidth: 100,
      maxWidth: 350,
      tooltipField: 'name',
    },
    {
      headerName: localization.advertisers.table.companyName,
      field: 'companyName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 100,
      maxWidth: 320,
      tooltipField: 'companyName',
    },
    {
      headerName: localization.advertisers.table.balance,
      field: 'balance',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'balanceRenderer',
      minWidth: 100,
      maxWidth: 350,
    },
    {
      headerName: 'Spend ($)',
      field: 'spend',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 100,
      maxWidth: 350,
    },
    {
      headerName: localization.advertisers.table.campaignsCount,
      field: 'campaignsCount',
      headerClass: 'ag-grid-header-cell',
      minWidth: 100,
      maxWidth: 390,
      tooltipField: 'campaignsCount',
    },
    {
      headerName: localization.advertisers.table.email,
      field: 'email',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'advPubMailRenderer',
      minWidth: 100,
      maxWidth: 650,
      tooltipField: 'email',
    },
    {
      headerName: localization.advertisers.table.status,
      field: 'status',
      cellRenderer: 'statusRenderer',
      headerClass: 'ag-grid-header-cell',
      minWidth: 80,
    },
    {
      headerName: localization.advertisers.table.registered,
      field: 'createdAt',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 150,
      width: 160,
      maxWidth: 350,
      tooltipField: 'createdAt',
    },
    {
      headerName: 'Action',
      cellRenderer: 'renderEditor',
      width: 200,
    },
  ],
};

