import localization from '../../../localization';

export const CAMPAIGNS_COLUMN_DEFS = {
  ADMIN: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 95,
      width: 95,
      maxWidth: 95,
    },
    {
      headerName: localization.campaigns.table.id,
      field: 'campaign.id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 60,
      width: 85,
      maxWidth: 100,
    },
    {
      headerName: localization.campaigns.table.campaign,
      field: 'campaign.campaignName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 150,
      maxWidth: 430,
      cellRenderer: 'campaignNameRenderer',
      tooltipField: 'campaignName',
    },
    {
      headerName: localization.campaigns.table.advertiser,
      field: 'campaign.advertiserName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 150,
      maxWidth: 350,
      tooltipField: 'userName',
    },
    {
      headerName: localization.campaigns.table.publishers,
      field: 'relatedPublishersCount',
      headerClass: 'ag-grid-header-cell',
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },

    {
      headerName: 'Type',
      field: 'campaign.modelPayment',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'modelRenderer',
      width: 80,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      headerName: 'Impressions',
      field: 'impressionsCount',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customNumberFormat',
      width: 120,
      minWidth: 120,
      maxWidth: 120,
    },
    {
      headerName: 'Clicks',
      field: 'clicksCount',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customNumberFormat',
      width: 80,
      minWidth: 80,
      maxWidth: 120,
    },
    {
      headerName: 'Conversions',
      field: 'conversionsCount',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customNumberFormat',
      width: 120,
      minWidth: 120,
      maxWidth: 120,
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      width: 100,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      headerName: 'CR (%)',
      field: 'cr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      width: 100,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      headerName: localization.campaigns.table.status,
      field: 'campaign.status',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'campaignStatusRenderer',
      width: 110,
      minWidth: 100,
      maxWidth: 250,
      tooltipField: 'campaign.statusReason',
    },
    {
      headerName: 'Revenue ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      headerName: 'Payout ($)',
      field: 'payout',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      width: 120,
      minWidth: 120,
      maxWidth: 250,
    },
    {
      headerName: 'Profit ($)',
      field: 'profit',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      width: 100,
      minWidth: 100,
    },
    {
      headerName: 'Labels',
      field: 'campaign.tags',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'tagsCellRenderer',
      minWidth: 120,
      maxWidth: 220,
    },
    {
      headerName: '',
      field: 'campaignsEditor',
      cellRenderer: 'renderEditor',
      width: 120,
      minWidth: 100,
      maxWidth: 200,
    },
  ],
  ACCOUNT_MANAGER: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 56,
      width: 56,
      maxWidth: 95,
    },
    {
      headerName: localization.campaigns.table.id,
      field: 'campaign.id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 40,
      width: 85,
      maxWidth: 100,
    },
    {
      headerName: localization.campaigns.table.campaign,
      field: 'campaign.campaignName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 90,
      maxWidth: 430,
      cellRenderer: 'campaignNameRenderer',
      tooltipField: 'campaignName',
    },
    {
      headerName: localization.campaigns.table.advertiser,
      field: 'campaign.advertiserName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 90,
      maxWidth: 350,
      tooltipField: 'userName',
    },
    {
      headerName: localization.campaigns.table.publishers,
      field: 'relatedPublishersCount',
      headerClass: 'ag-grid-header-cell',
      width: 120,
      minWidth: 100,
      maxWidth: 250,
    },

    {
      headerName: 'Type',
      field: 'campaign.modelPayment',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'modelRenderer',
      width: 80,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      headerName: 'Impressions',
      field: 'impressionsCount',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customNumberFormat',
      width: 80,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      headerName: 'clicks',
      field: 'clicksCount',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customNumberFormat',
      width: 80,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      headerName: 'Conversions',
      field: 'conversionsCount',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customNumberFormat',
      width: 80,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      width: 100,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      headerName: 'CR (%)',
      field: 'cr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      width: 100,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      headerName: localization.campaigns.table.status,
      field: 'campaign.status',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'campaignStatusRenderer',
      width: 110,
      minWidth: 100,
      maxWidth: 250,
      tooltipField: 'campaign.statusReason',
    },
    {
      headerName: 'Revenue ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      width: 100,
      minWidth: 90,
      maxWidth: 250,
    },
    {
      headerName: 'Payout ($)',
      field: 'payout',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      width: 100,
      minWidth: 90,
      maxWidth: 250,
    },
    {
      headerName: 'Profit ($)',
      field: 'profit',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      width: 100,
      minWidth: 100,
    },
    {
      headerName: 'Labels',
      field: 'campaign.tags',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'tagsCellRenderer',
      minWidth: 50,
      maxWidth: 220,
    },
  ],
  ADVERTISER: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 56,
      width: 56,
      maxWidth: 95,
    },
    {
      headerName: localization.campaigns.table.id,
      field: 'campaign.id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 40,
      width: 85,
      maxWidth: 100,
    },
    {
      headerName: localization.campaigns.table.campaign,
      field: 'campaign.campaignName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 90,
      maxWidth: 230,
      cellRenderer: 'campaignNameRenderer',
      tooltipField: 'campaignName',
    },
    {
      headerName: 'Type',
      field: 'campaign.modelPayment',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'modelRenderer',
      width: 80,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      headerName: 'impressions',
      field: 'impressionsCount',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customNumberFormat',
      minWidth: 50,
      maxWidth: 120,
    },
    {
      headerName: 'clicks',
      field: 'clicksCount',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customNumberFormat',
      width: 80,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      headerName: 'CTR (%)',
      field: 'ctr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      width: 100,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      headerName: 'conversions',
      field: 'conversionsCount',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customNumberFormat',
      width: 80,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      headerName: 'CR (%)',
      field: 'cr',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      width: 100,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      headerName: 'Spend ($)',
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'amountCellRenderer',
      width: 100,
      minWidth: 90,
      maxWidth: 250,
    },
    {
      headerName: 'Labels',
      field: 'campaign.tags',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'tagsCellRenderer',
      minWidth: 50,
      maxWidth: 220,
    },
    {
      headerName: localization.campaigns.table.status,
      field: 'campaign.status',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'campaignStatusRenderer',
      width: 110,
      minWidth: 100,
      maxWidth: 250,
    },
  ],
  PUBLISHER: [
    {
      headerName: localization.campaigns.table.campaignId,
      field: 'campaign.id',
      headerClass: 'ag-grid-header-cell',
      width: 110,
      minWidth: 65,
      maxWidth: 210,
    },
    {
      headerName: localization.campaigns.table.campaign,
      field: 'campaign.campaignName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 100,
      maxWidth: 430,
      // cellRenderer: 'campaignNameRenderer',
      tooltipField: 'campaignName',
    },
    {
      headerName: localization.campaigns.table.link,
      field: 'campaign.campaignName',
      headerClass: 'ag-grid-header-cell',
      minWidth: 100,
      maxWidth: 430,
      cellRenderer: 'campaignLinkRenderer',
      tooltipField: 'campaignName',
    },
    {
      headerName: 'Geo',
      field: 'geography',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'countryRenderer',
    },
    {
      headerName: localization.campaigns.table.payouts,
      field: 'ownerSpent',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'payoutRenderer',
      width: 100,
      minWidth: 100,
      maxWidth: 250,
    },
    {
      headerName: 'Type',
      field: 'campaign.modelPayment',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'modelRenderer',
      width: 80,
      minWidth: 50,
      maxWidth: 120,
    },
    {
      headerName: localization.campaigns.table.platform,
      field: 'campaign.platform',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'platformRenderer',
      width: 100,
      minWidth: 50,
      maxWidth: 210,
    },
    {
      headerName: localization.campaigns.table.device,
      field: 'campaign.deviceType',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'deviceRenderer',
      width: 100,
      minWidth: 50,
      maxWidth: 210,
    },
  ],
};
