import localization from '../../../localization';

export default {
  ADMIN: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 95,
      width: 95,
      maxWidth: 95,
    },
    {
      headerName: localization.publishers.table.id,
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      width: 85,
      maxWidth: 100,
    },
    {
      headerName: localization.publishers.table.name,
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'advPubRenderer',
      width: 150,
      minWidth: 100,
      maxWidth: 320,
      tooltipField: 'name',
    },
    {
      headerName: localization.publishers.table.companyName,
      field: 'companyName',
      headerClass: 'ag-grid-header-cell',
      width: 150,
      minWidth: 100,
      maxWidth: 320,
      tooltipField: 'companyName',
    },
    {
      headerName: localization.publishers.table.payout,
      field: 'revenue',
      headerClass: 'ag-grid-header-cell',
      minWidth: 70,
      maxWidth: 200,
      cellRenderer: 'amountCellRenderer',
      tooltipField: 'ownerSpent',
    },
    {
      headerName: localization.publishers.table.connectedCampaigns,
      field: 'campaignsCount',
      headerClass: 'ag-grid-header-cell',
      minWidth: 70,
      maxWidth: 270,
    },
    {
      headerName: 'QPS',
      field: 'qps',
      headerClass: 'ag-grid-header-cell',
      width: 150,
      minWidth: 100,
      maxWidth: 320,
      cellRenderer: 'customNumberFormat',
    },
    {
      headerName: 'Email',
      field: 'email',
      headerClass: 'ag-grid-header-cell',
      minWidth: 100,
      maxWidth: 650,
      tooltipField: 'email',
    },
    {
      headerName: localization.publishers.table.status,
      field: 'status',
      cellRenderer: 'statusRenderer',
      headerClass: 'ag-grid-header-cell',
      minWidth: 70,
      maxWidth: 120,
    },
    {
      headerName: localization.publishers.table.registered,
      field: 'createdAt',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 150,
      width: 160,
      maxWidth: 350,
      tooltipField: 'createdAt',
    },
    {
      headerName: 'Action',
      checkboxSelection: false,
      cellRenderer: 'renderEditor',
      width: 150,
    },
  ],
  ACCOUNT_MANAGER: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 35,
      width: 40,
      maxWidth: 95,
    },
    {
      headerName: localization.publishers.table.id,
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      width: 85,
      maxWidth: 100,
    },
    {
      headerName: localization.publishers.table.name,
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'advPubRenderer',
      width: 150,
      minWidth: 100,
      maxWidth: 320,
      tooltipField: 'name',
    },
    {
      headerName: localization.publishers.table.companyName,
      field: 'companyName',
      headerClass: 'ag-grid-header-cell',
      width: 150,
      minWidth: 100,
      maxWidth: 320,
      tooltipField: 'companyName',
    },
    {
      headerName: localization.publishers.table.payout,
      field: 'payout',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'customToFixed',
      minWidth: 70,
      maxWidth: 200,
      tooltipField: 'payout',
    },
    {
      headerName: localization.publishers.table.connectedCampaigns,
      field: 'connected',
      headerClass: 'ag-grid-header-cell',
      minWidth: 70,
      maxWidth: 270,
      tooltipField: 'connected',
    },
    {
      headerName: 'Email',
      field: 'email',
      headerClass: 'ag-grid-header-cell',
      minWidth: 100,
      maxWidth: 650,
      tooltipField: 'email',
    },
    {
      headerName: 'Type',
      field: 'channel',
      cellRenderer: 'channelRenderer',
      headerClass: 'ag-grid-header-cell',
      minWidth: 70,
      maxWidth: 120,
    },
    {
      headerName: localization.publishers.table.status,
      field: 'status',
      cellRenderer: 'statusRenderer',
      headerClass: 'ag-grid-header-cell',
      minWidth: 70,
      maxWidth: 120,
    },
    {
      headerName: localization.publishers.table.registered,
      field: 'createdAt',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 150,
      width: 160,
      maxWidth: 350,
      tooltipField: 'createdAt',
    },
    {
      headerName: 'Action',
      checkboxSelection: false,
      cellRenderer: 'renderEditor',
      width: 150,
    },
  ],
};
