export default {
  ADMIN: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 50,
      maxWidth: 95,
    },
    {
      headerName: 'id',
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 90,
    },
    {
      headerName: 'name',
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'siteNameRenderer',
      minWidth: 50,
      maxWidth: 200,
    },
    {
      headerName: 'domain',
      field: 'domain',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 200,
    },
    {
      headerName: 'publisher name',
      field: 'publisher.name',
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 230,
    },
    {
      headerName: 'banners count',
      field: 'banners',
      valueFormatter: ({data}) => data.banners && data.banners.length || 0,
      headerClass: 'ag-grid-header-cell',
      minWidth: 50,
      maxWidth: 230,
    },
    {
      headerName: 'status',
      field: 'status',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'statusRenderer',
      minWidth: 50,
      maxWidth: 230,
    },
    {
      headerName: 'created',
      field: 'createdAt',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      minWidth: 50,
      maxWidth: 150,
    },
    {
      checkboxSelection: false,
      cellRenderer: 'actionsRenderer',
      minWidth: 50,
      maxWidth: 150,
    },
  ],
  ACCOUNT_MANAGER: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 56,
      width: 56,
      maxWidth: 95,
    },
    {
      headerName: 'id',
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      width: 90,
    },
    {
      headerName: 'name',
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'siteNameRenderer',
      width: 200,
    },
    {
      headerName: 'domain',
      field: 'domain',
      headerClass: 'ag-grid-header-cell',
      width: 200,
    },
    {
      headerName: 'publisher name',
      field: 'publisher.name',
      headerClass: 'ag-grid-header-cell',
      width: 220,
    },
    {
      headerName: 'banners count',
      field: 'banners.length',
      valueFormatter: ({data}) => data.banners && data.banners.length || 0,
      headerClass: 'ag-grid-header-cell',
      width: 150,
    },
    {
      headerName: 'status',
      field: 'status',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'statusRenderer',
      width: 120,
    },
    {
      headerName: 'created',
      field: 'createdAt',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      width: 120,
    },
    {
      checkboxSelection: false,
      cellRenderer: 'actionsRenderer',
      minWidth: 50,
      maxWidth: 150,
    },
  ],
  PUBLISHER: [
    {
      headerClass: 'ag-grid-header-cell',
      headerCheckboxSelection: true,
      headerCheckboxSelectionFilteredOnly: true,
      checkboxSelection: true,
      minWidth: 56,
      width: 56,
      maxWidth: 95,
    },
    {
      headerName: 'id',
      field: 'id',
      headerClass: 'ag-grid-header-cell',
      width: 90,
    },
    {
      headerName: 'name',
      field: 'name',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'siteNameRenderer',
      width: 220,
    },
    {
      headerName: 'domain',
      field: 'domain',
      headerClass: 'ag-grid-header-cell',
      width: 220,
    },
    {
      headerName: 'banners count',
      field: 'banners.length',
      valueFormatter: ({data}) => data.banners && data.banners.length || 0,
      headerClass: 'ag-grid-header-cell',
      width: 150,
    },
    {
      headerName: 'status',
      field: 'status',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'statusRenderer',
      width: 120,
    },
    {
      headerName: 'created',
      field: 'createdAt',
      headerClass: 'ag-grid-header-cell',
      cellRenderer: 'dateCellRenderer',
      width: 120,
    },
    {
      checkboxSelection: false,
      cellRenderer: 'actionsRenderer',
      minWidth: 50,
      maxWidth: 150,
    },
  ],
};
