export default {
  Notifications: {
    notification: "Notification",
    MarkAllRead: "Mark as all read",
    view: "View",
    markRead: "Mark as read",
    allUnread: "You've not read any notifications from the last 30 days.",
    allRead: "You've read all your notifications from the last 30 days.",
    end: "That's all",
    all: "There is no new notification"
  },
  addFunds: {
    currentBalance: "Current balance",
    addFunds: "Add funds To your account",
  },
  status: {
    new: "New",
    active: "Active",
    paused: "Paused",
    pending: "Pending",
    rejected: "Rejected",
  },
  advertisers: {
    title: "Advertisers",
    filters: {
      name: "Name",
      campaignName: "Name",
      manager: "Manager",
      country: "Country",
      status: "Status",
      search: "Search advertiser by name, company etc",
    },
    table: {
      id: "Id",
      name: "Name",
      companyName: "Company",
      balance: "Balance ($)",
      campaign: "Campaign name",
      manager: "Manager",
      country: "Country",
      email: "Email",
      taxId: "Tax id",
      skype: "Skype",
      registered: "Registered",
      campaignsCount: "Campaigns",
    },
    createAdvertiser: {
      title: "Create an advertiser",
    },
    updateAdvertiser: {
      title: "Update advertiser",
    },
    goBack: "Back to advertisers view",
  },
  agreementPage: {
    desc: "Dear partner, following the upcoming changes in REGULATION (EU) 2016/679 OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation) we are updating our policy and T&C accordingly.",
    accept: "  I accept the terms and conditions",
    agree: "Agree",
  },
  activationResult: {
    expired: "Activation link is expired",
    activated: "Your account has been activated",
    broken: "Activation link is broken, or there are no such user",
  },
  account: {
    title: "Account information",
    address_details: "Address details",
    email: "Email",
    password: "Password",
    firstName: "First name",
    lastName: "Last name",
    address: "Address",
    city: "City",
    country: "Country",
    zipcode: "Postal code",
    corporation: "Corporation",
    companyName: "Company name",
    billingAddress: "Billing address",
    vatTax: "VAT number/ Tax ID",
    desc: "If you are looking to make changes to your legal information , please open a support ticket",
    link: "here",
    name: "Name",
    contactManager: "or contact your Account Manager",
    accountType: "Account Type",
    trafficChanel: "Traffic channel",
    role: "Role",
  },
  billingDetails: {
    title: "Billing details",
    personalData: "Personal details",
    corpbillingDet: "Corporate details",
    settings: "Settings & static URL",
    form: {
      firstName: "First name*",
      lastName: "Last name*",
      address: "Address",
      city: "City",
      companyCity: "Company city",
      zipcode: "Postal code",
      companyName: "Company name*",
      corporation: "Corporation",
      country: "Country",
      companyCountry: "Country",
      vatTax: "VAT number / Tax ID",
      billingAddress: "Billing address",
    },
  },
  billing: {
    title: "Transaction history",
    billing: "Billing",
    filters: {
      today: "Today so far",
      startDate: "Start date",
      endDate: "End date",
      user: "User",
      campaign: "Campaign",
      status: "Status",
      selectPeriod: "Select period",
    },
  },
  campaigns: {
    title: "Campaigns",
    overviewCampaign: "Overview campaign",
    trackingLink: "Tracking link",
    geo: "Geography",
    notActive:
      "Campaigns are not active and are not being approved. Please add",
    addFunds: "funds to your account $",
    createCampaign: "Create new campaign",
    reach: "Reach",
    engage: "Engage",
    search: "Search by campaign type, status etc.",
    filters: {
      country: "Country",
      campaignType: "Campaign type",
      campaignModel: "Campaign model",
      os: "OS",
      model: "Model",
      status: "Status",
      users: "Users",
      advertisers: "Advertisers",
      spent: "Spent",
      orderType: "Order type",
      startFor: "Start for",
      today: "Today",
      yesterday: "Yesterday",
      lastSeven: "Last 7 days",
      lastThirty: "Last 30 days",
      customRange: "Custom range",
    },
    goBack: "Back to campaigns view",
    table: {
      campaign: "Campaign",
      advertiserBid: "Bid",
      status: "Status",
      statusReason: "Reason",
      access: "Access",
      channel: "Channel",
      from: "From",
      clicks: "Clicks",
      link: "Link",
      installs: "Conversions",
      cr: "CR (%)",
      ctr: "CTR (%)",
      publishers: "Publishers",
      kpi: "KPI",
      platform: "Platform",
      payouts: "Payout ($)",
      user: "User",
      revenue: "Revenue ($)",
      campaignId: "Id",
      id: "Id",
      advertiser: "Advertiser",
      device: "Device",
      bidType: "Bid type",
    },
    inventories: {
      table: {
        appSite: "App/Site",
        dailyImpres: "Daily impressions",
        aveCpm: "Average CPM",
      },
    },
    dataPartners: {
    estDataCost : 'Est data cost :',
    createNewGroup : 'Create new group',
    betweenSegments : 'Between Segments',
    clearAll : 'Clear All',
    pleaseSelectTheFilter : 'Please select the partners filter',
    showing : 'Showing',
    segments : 'segments',
    segmentActivation : 'Segment activation',
    mySegments : 'My segments',
    thirdPartySegments : 'Third party segments',
    createAudience : 'Create audience'
  }
  },
  createCampaign: {
    title: "Choose the advertising channel that best fits your goals",
    titleAdd: "Choose ad type",
    createBtn: "Create campaign",
    campaignDescription: {
      cpm: " campaign refers to advertising bought on the basis of impression",
    },
  },
  createCampaignForm: {
    publisherTestingLink: {
      title: "Publisher testing links",
      labels: {
        publisherName: "Publisher name",
        trafficType: "traffic Type",
      },
    },
    campaignTracking: {
      title: "Campaign info and tracking",
      labels: {
        campaignDescription: "Description",
        testingLink: "Testing URL",
        advertiserName: "Advertiser name*",
        modelPayment: "Payment model",
        status: "Status",
        accessStatus: "Access status",
        deliveryType: "Delivery Type",
        advertisingChannel: "Advertising channel",
        campaignName: "Campaign name*",
        campaignCat: "Campaign category",
        appLink: "App Link*",
        prevLink: "Preview Link*",
        trackingURL: "Tracking URL*",
        conversionTrackingTag: "Conversion tracking tag",
        adURL: "Ad URL",
        campaignURL: "Campaign URL*",
        impressionURL: "Impression URL",
        postbackURL: "Postback URL",
        topLevel: "Top level domain*",
        title: "Title*",
        description: "Description*",
        notification: "Notification",
        startEndDate: "Start/End date",
        copyrighting: "Copyright*",
        antiFraud: "Exclude campaign from anti-fraud",
        antiFraudDet: "Anti-fraud optimisation",
        excludeAdultIllegal: "Exclude adult and illegal content",
        disableTest: "Disable link-testing",
        disableAppLink: "Disable app link",
        disableConversionTest: "Disable conversion-testing",
        crThreshold: "CR threshold",
        kpi: "KPI",
        lifespan: "Click lifespan",
        frequencyCapImpression: "Frequency capping per impression",
        frequencyCapClick: "Frequency capping per click",
        advancedOpt: "Advanced options",
        hourlyBudget: "Hourly budget",
        bidRequestParam: "Required bid requests parameters",
        languages: "Languages",
      },
      fields: {
        requiredMacros: "Choose required macros id",
        optionalMacros: "Choose optional macros",
        clickid: "CLICK_ID",
        publisheruuid: "PUBLISHER_ID",
        deviceid: "DEVICE_ID",
        appBundle: "APP_BUNDLE",
        appName: "APP_NAME",
        ifa: "IFA",
        auctionPrice: "AUCTION_PRICE",
        crid: "CR_ID",
        ip: "IP",
        emailMe: "Email me at",
        start: "Start",
        startUntil: "(Start 12/12/2019 until 12/12/2020)",
        percentsBudget: "Email me daily and campaign budget at",
        confirmCopyrighting:
          "I confirm that any material offered in this campaign are owned by or licensed to me",
        lowest: "Lowest",
        highest: "Highest",
        soft: "Soft",
        hard: "Hard",
        antiFraudDesc:
          "With fraud detection, all sub IDs with fraud rate of more than 30% after 25 installs will be blocked.",
        paused: "Paused",
        active: "Active",
        disable: "Disable",
        enable: "Enable",
        noCap: "No cap on impression",
        capIp: "Cap per IP",
        capDevice: "Cap per device",
        bundleID: "Bundle ID",
        siteID: "Site ID",
        subID: "Sub ID",
        COPPA: "COPPA",
        GDPR: "GDPR compliant",
        deviceID: "Device ID",
        gdpr: "GDPR compliant",
        idfa: "IDFA",
        googleAd: "GoogleADID",
        dpid: "DPID",
        did: "DID",
        include: "Include",
        exclude: "Exclude",
        ipRang: "Enter IP ranges",
        cidrIpAdd: "Enter CIDR IP address",
        impressionPerDay: "Impressions per day",
        invPayout: "Payout %",
        impressionPer: "Impressions per",
        consistent: "Consistent bidding",
        eager: "Accelerated bidding",
        capDuration: "Duration",
        deliveryTooltip:
          "Accelerated Bidding: bid on all the traffic that is accessible.\n" +
          "Consistent Bidding: use our pacing algorithm to consistent bid in one day.",
      },
      desc: {
        publicAccess: "campaign opened to everyone",
        privateAccess:
          "campaign opened to 0 pubs , until you assign/whitelist pubs to the campaign",
        hardAvaliable: " The Hard KPI available only for the managed accounts",
      },
    },
    goal: {
      title: "Goals",
      payout: "payout",
    },
    targeting: {
      title: "Targeting",
      labels: {
        dayParting: "Campaign scheduling",
        geography: "Geography",
        age: "Age",
        platform: "Platform",
        country: "Country",
        city: "City",
        state: "State",
        deviceType: "Device type",
        inventoryType: "Inventory type",
        connections: "Connections",
        trafficType: "Traffic type",
        gender: "Gender",
      },
      fields: {
        all: "All",
        both: "Both",
        custom: "Custom",
        mobile: "Mobile",
        tablets: "Tablets",
        desktop: "Desktop",
        connectedTV: "Connected TV",
        carrier: "Carrier",
        wifi: "WiFi",
        female: "Female",
        male: "Male",
        enable: "Enable",
        disable: "Disable",
      },
      desc: {},
    },
    inventoryControl: {
      title: "Inventory control",
      labels: {
        inventSource: "Select inventory source",
        selectApp: "Select app/sites",
        availableInv: "Search inventories",
        myInvent: "My inventories",
        pmpSupport: "PMP Support",
      },
    },
    audiences: {
      title: "Audiences"
    },
    creatives: {
      title: "Creatives",
      labels: {
        uploadCreatives: "Upload creatives for your campaign.",
        tag: "JS/HTML tag",
        tagLabel: "Tag",
        requiredMacros: "Required macros",
        optionalMacros: "Choose required macros id(optional)",
        bannerUrl: "BANNER_URL",
        impressionUrl: "IMPRESSION_URL",
        clickUrl: "CLICK_URL",
        impressionUrlLabel: "Impression URL",
        image: "Upload creative",
      },
      validate: {
        bannerUrlMacros: "Macros BANNER_URL is required",
        impressionUrlMacros: "Macros IMPRESSION_URL is required",
      },
      table: {
        name: "Name",
        resolution: "Resolution",
        size: "Size",
        preview: "Preview",
      },
    },
    videoCreatives: {
      labels: {
        impressionPixel: "Impression pixel",
        videoDuration: "Duration",
        startDelay: "Start delay",
        endCard: "End card",
        video: "Video",
        image: "Image",
        videoUrl: "VIDEO_URL",
        impressionUrl: "IMPRESSION_URL",
        clickUrl: "CLICK_URL",
        endCardUrl: "ENDCARD_URL",
        delay: "DELAY",
        requiredMacros: "Required macros",
        optionalMacros: "Optional macros",
      },
      validate: {
        videoUrlMacros: "Macros VIDEO_URL is required",
        impressionUrlMacros: "Macros IMPRESSION_URL is required",
        greater: "Video duration should be greater or equal 5 sec",
        less: "Video duration should be less or equal to 60 sec",
      },
    },
    audioCreatives: {
      labels: {
        impressionPixel: "Impression pixel",
        audioDuration: "Duration",
        startDelay: "Start delay",
        endCard: "End card",
        audio: "Video",
        image: "Image",
        audioUrl: "VIDEO_URL",
        impressionUrl: "IMPRESSION_URL",
        clickUrl: "CLICK_URL",
        endCardUrl: "ENDCARD_URL",
        delay: "DELAY",
        requiredMacros: "Required macros",
        optionalMacros: "Optional macros",
      },
      validate: {
        audioUrlMacros: "Macros AUDIO_URL is required",
        impressionUrlMacros: "Macros IMPRESSION_URL is required",
        greater: "Audio duration should be greater or equal 5 sec",
        less: "Audio duration should be less or equal to 60 sec",
      },
    },
    creativesNativeAds: {
      title: "Creatives",
      labels: {
        creativeName: "Title*",
        creativeCta: "CTA*",
        creativeSponsored: "Sponsored*",
        creativeRating: "Select app rating",
        creativeDescription: "Description*",
        creativeIconImage: "Upload creative*",
        creativeMainImage: "Main Image*",
      },
      tooltips: {
        creativeName: "Main title or headline of your ad",
        creativeSponsored:
          "Brand/Advertiser name of your ad. Maximum length: 30 characters",
        creativeRating: "App rating in the stores",
        creativeDescription:
          "Set a text description for your ad. Maximum length: 100 characters. Adview supported maximum length: 16 characters.",
        creativeCta:
          'Call-To-Action Text. Usually "Install" is the default text. Other recommended texts: Install Now, Download, Sign Up, Learn More, Play, Play Game.Maximum length: 15 characters.',
      },
    },
    budgetSchedule: {
      title: "Budget and schedule",
      titleBudget: "Budget",
      labels: {
        publisherPayout: "Publisher payout",
        dailyBudget: "Daily budget",
        bid: "Max Bid*",
        totalBudget: "Total budget",
        bidType: "Bid type",
      },
      fields: {
        atLeast: "must be at least $0.2",
        unlimited: "Unlimited",
      },
      desc: {},
    },
  },
  dashboard: {
    summaryStat: {
      imToday: "Impressions",
      clickToday: "Clicks",
      convToday: "Conversions",
      ecpaToday: "eCPA",
      spentToday: "Revenue",
      earnedToday: "Payout",
      ctrToday: "CTR%",
      crToday: "CR%",
      today: "Today",
      yesterday: "Yesterday",
      availableBalance: "Available balance",
      sevenDays: "Last 7 days",
      thisMonth: "This month",
      lastMonth: "Last month",
      thisYear: "This year",
      ctr: "CTR",
      cr: "Conversion rate (CR)",
      winRate: "WinRate",
    },
    chart: {
      impressions: "Impressions",
      bidrequests: "Requests",
      bidresponses: "Responses",
      clicks: "Clicks",
      conversions: "Conversions",
      winrate: "WinRate",
      fillrate: "Fill Rate",
      revenue: "Revenue",
      profit: "Profit",
      ctr: "CTR %",
      cr: "CR %",
      ecpa: "eCPA",
      spend: "Spend",
    },
    table: {
      campaigns: "Campaigns",
      campaign: "Campaign",
      profit: "Profit",
      publishers: "Publishers",
      period: "Period",
      type: "Type",
      progress: "Progress",
      app: "App",
      platform: "Platform",
    },
    dropdown: {
      day: "Day",
      hour: "Hour",
      month: "Month",
      year: "Year",
      budget: "Budget",
      period: "Period",
      type: "Type",
    },
    trafficStatistics: "Performance:",
    pendingPublishers: "Pending publishers",
    activePublishers: "Active publishers",
    activeCampaigns: "Active campaigns",
    topCampaigns: "Top 5 campaigns",
    network: " in our network",
    topPublishers: "Top 5 publishers",
    topCaps: "Caps top 5",
    topGeo: "Geography: Top 10 countries",
    top5countries: "Top 5 spend country-wise",
    noData: "No data available",
  },
  integration: {
    trafficType: "Inventory type",
    credentials: "API credentials",
    keys: "API keys",
    urlApi: "API URL",
    credentDesc:
      "You can use the DSP features in third-party applications through our API",
    explore: "Explore our",
    documentation: "API documentation",
    xml: "Integration specification",
    keysDesc:
      "URL to get details about all available campaigns for publisher (mostly used for performance based campaigns)",
    generateKey: "Generate key",
    clipboard: "Copy to clipboard",
    refresh: "Refresh",
    regenerate: "Generate key",
    urlDesc: "Do not share your credentials with anyone to keep your data safe",
    copied: "Copied",
    statsUrlDesc: "URL to provide statistic to publisher",
    statsUrlDescFrom: "URL to get statistic from publisher",
    campaign: "Campaign",
    url: "Campaigns URL",
    reportUrl: "Statistics URL",
    enableRTB: "RTB",
    enableDirectPublisher: "Direct publisher",
    protocol: "Protocol",
    makePaymentsWith: "Calculate payout with",
    enable: "Enable",
    openRTBVersions: "Version",
    adType: "Ad Type",
    dataCenterLocation: "Data center location",
    autoConnectDemand: "Auto-connect all demand",
    bidderUrl: "Bidder endpoint",
    tMax: "Min Timeout (ms)",
    auctionType: "Auction type",
    fallback: "fallback link",
  },
  inventoryControl: {
    title: "Inventory control",
    labels: {
      inventSource: "Select inventory source",
      selectApp: "Select app/sites",
      availableInv: "Available inventories",
      myInvent: "My inventories",
      pmpSupport: "PMP support",
    },
  },

  publishers: {
    title: "Publishers",
    filters: {
      name: "Name",
      companyName: "Company name",
      status: "Status",
      manager: "Manager",
      type: "Ad type",
    },
    table: {
      id: "Id",
      name: "Name",
      companyName: "Company",
      registered: "Registered",
      manager: "Manager",
      payout: "Payout ($)",
      connectedCampaigns: "Campaigns",
      description: "Description",
      status: "Status",
    },
    createPublisher: {
      title: "Create a publisher",
    },
    updatePublisher: {
      title: "  Update publisher",
    },
    form: {
      whatDescribe: "What describes you best?*",
      channel: "Channel",
      mediaBuying: "Media buying team",
      adNetwork: "Ad network",
      affiliateNetwork: "Publisher network",
      adAgency: "Ad agency",
      ssp: "SSP",
    },
    goBack: "Back to publishers view",
    generate: "Generate",
    upload: "Upload",
  },
  tools: {
    title: "Tools",
    settings: "Settings",
    antiFraud: "Anti-fraud",
    advApi: "Advertiser API integration",
    results: "Results",
    optimization: "Optimization",
    customNav: "Custom",
    block: "Block",
    low: "low",
    high: "high",
    advertiser: "Advertiser",
    blockLow: "Block low",
    blockHigh: "Block high",
    Publisher: "Publisher",
    campaign: "Campaign",
    endUrl: "End URL",
    whitelist: "Whitelist / Blacklist",
    goBackSet: "Back to setting view",
    custom: {
      custom: "Custom",
      campaigns: "Campaigns",
      campaignWhiteList: "Campaign whitelist",
      blackId: "Blacklist - Enter Sub ID's to block",
      whiteId: "Whitelist - Enter Sub ID's to whitelist",
      blackReason: "Blacklist reasons",
      lowPerform: "Low performance",
      kpiNot: "KPI not reached",
      lowSecond: "Low second day RR retention rate",
      asFraud: "0 performance(suspicious as fraud)",
      campaignId: "Campaign Id",
      publisherId: "Publisher Id",
      subId: "Sub Id",
      type: "Type",
      value: "Value",
      blacklist: "Blacklist",
      whitelist: "Whitelist",
      selectCampaign: "Select campaign",
      selectAdv: "Select advertiser",
    },
  },
  reports: {
    title: "Reports",
    download: "Download",
    generate: "Generate",
    addCol: "Add Columns:",
    filters: {
      kpiType: {
        soft: "Soft",
        hard: "Hard",
      },
      startDate: "Start date",
      endDate: "End date",
      advertiser: "Advertiser",
      campaign: "Campaign",
      campaignStatus: "Campaign status",
      country: "Country",
      spentMin: "Spent min",
      spentMax: "Spent max",
    },
    type: {
      daily: "Daily",
      conversions: "Conversions",
      advertisers: "Advertisers",
      countries: "Countries",
      cities: "Cities",
      devices: "Devices",
      serversPostbacks: "Servers postbacks",
      retentionRate: "Retention rate",
      fraudShield: "Fraud shield",
      campaigns: "Campaigns",
    },
    table: {
      status: {
        test: "Test",
        paused: "Paused",
        active: "Active",
      },
      date: "Date",
      clicks: "Clicks",
      conversions: "Conversions",
      revenue: "Revenue",
      payouts: "Payouts",
      earnings: "Profit",
      spent: "Spent",
    },
  },
  users: {
    title: "Users",
    goBack: "Back to user view",
    form: {
      skype: "Skype",
      roles: "Define the role",
      owner: "Owner",
      administrator: "Administrator",
      accountManager: "Account manager",
      sectors: "Sectors",
      rules: "User permissions",
      statistic: "Statistic",
      newUser: "New user & permissions",
      updateUser: "Update user & permissions",
    },
    table: {
      email: "Email",
      name: "Name",
      role: "Role",
      status: "Status",
    },
    filters: {
      role: "Role",
      status: "Status",
    },
  },
  logs: {
    title: "Logs",
    filters: {
      today: "Today so far",
      startDate: "Start date",
      endDate: "End date",
      user: "User",
      campaign: "Campaign",
      type: "Type",
      selectPeriod: "Select period",
    },
    table: {
      user: "User",
      type: "Type",
      changedObject: "Changed object",
      details: "Details",
      note: "Note",
      date: "Date",
      activityDetails: "Activity details",
    },
    modal: {
      activity: "Activity",
      changedField: "Changed Field",
      details: "Details",
      oldValue: "Old value",
      newValue: "New value",
    },
  },
  targeting: {
    include: "Include",
    exclude: "Exclude",
  },
  header: {
    companyName: "DSP",
    manager: "Your account manager",
    myAccount: "My account",
    helpFaq: "Help & FAQs",
    settings: "Settings",
    signOut: "Sign out",
    nav: {
      dashboard: "Dashboard",
      advertisers: "Advertisers",
      publishers: "Publishers",
      sites: "Sites",
      campaigns: "Campaigns",
      reports: "Reports",
      integration: "Integration",
      audience: "Audience",
      billing: "Billing",
      tools: "Tools",
      settings: "Settings",
      addFunds: "Add credits",
      createCampaign: "Create a campaign",
      backToAdmin: "Back to admin",
      users: "Users",
      logs: "Logs",
      signPublisher: "Sign in as publisher",
      signAdvertiser: "Sign in as advertiser",
      signAdmin: "Sign in as admin",
      signManager: "Sign in as manager",
      test: "Test",
    },
  },
  forms: {
    addNew: "Add",
    publisherLink: "Publisher outer link",
    signIn: "Sign in",
    signOut: "Sign out",
    login: "Login",
    signUp: "Sign Up",
    create: "Create",
    cancel: "Cancel",
    clear: "Clear",
    save: "Save",
    payout: "Payout",
    saveAndExit: "Save and Exit",
    copy: "Copy",
    generate: "Generate",
    applyFilters: "Apply",
    continue: "Continue",
    accept: "Accept",
    send: "Send",
    register: "Register",
    submit: "Submit",
    view: "View",
    back: "Back",
    ok: "Ok",
    run: "Run",
    signInTitle: "Please, sign in to your account",
    resetPasswordTitle: "Reset your password",
    yourRole: " Your role",
    add: "Add",

    signInAs: "Sign In as ",
    search: "Search...",
    filter: "Filter...",
    name: "Name*",
    email: "Email*",
    companyName: "Company name",
    manager: "Manager",
    skype: "Skype",
    balance: "Balance ($)",
    confirmPassword: "Confirm password*",
    password: "Password*",
    newPassword: "New Password*",
    forgotPassword: "Forgot password?",
    noAccount: "Don't have an account?",
    passwordChanged: "Password changed",
    postbackUrl: "Publisher Postback URL",
  },
  footer: {
    copyright: "Rebid media",
    privacyPolicy: "Privacy policy",
  },
  forgotPassword: {
    desc: "Please check your inbox",
  },
  validate: {
    required: "Required",
    invalidEmail: "Invalid email",
    invalidDate: "Invalid date",
    invalid: "Invalid",
    emptyPasswordField: "Password field is empty",
    invalidFormat: "Invalid format",
    passwordLong:
      "A minimum 8 characters password contains a combination of uppercase and lowercase letter and number are required (0-9, a-z, A-Z)",
    passwordMatch: "Passwords didn't match",
    passwordFormat: "Password must contains only alphanumeric characters",
    macros: "Macros CLICK_ID is required",
    invalidUrl: "Invalid url",
    invalidMacros: "Invalid macros",
    invalidDomain: "Invalid domain names",
    mustAtLeast: "must be at least 0.2$",
    mustAtLeastCPM: "must be at least 0.1$",
    mustAtLeastCPMCap: "must be at least 100",
    mustAtPercent: "must be at 0-100",
    mustAtLeastMaxBid: "must be at least max bid",
    appNotFound: "App not found",
    zipCode: "Invalid postal code format",
    maxLength: "Max length is {0} characters",
    mustCap: "Must be at least 1",
    dateRangeInvalid: "Invalid date range",
    lessThanTotalBudget: "Must be less than total budget",
    integersOnly: "Integers only",
    alphanumericOnly: "Alphanumeric only",
    valueIsNotNumber: "Invalid input value. Only numbers are allowed",
    valueIsNotInteger:
      "Invalid input value. Only positive integers are allowed",
    maxValue: "Can't be more than {0}",
  },
  verify: {
    resend: "Re-send activation email",
    verified:
      "Your account is being verified. An account manager will get in touch with you within 48h.",
    activate:
      "Please, activate your account via activation link in the received e-mail",
    reject: "Your account has been rejected",
    banned: "Your account has been paused",
    activation: "Activation email sent",
  },
  confirm: {
    backToAdmin: "You will sign out and back to admin portal",
    deactivateUser: "{0} will be deactivated",
    deactivateCampaign: "Campaign will be deactivated",
    signInAs: "You will sign in as {0}",
    deleteAdvertiserSingle:
      "Are you sure you want to delete adveriser. All campaigns associated with it will be deleted as well",
    deleteAdvertiserMulti:
      "Are you sure you want to delete adverisers. All campaigns associated with it will be deleted as well",
    changeAdvertisingChannel:
      "Whitelist and blacklist will be re-init after save",
    updateInventorySection:
      "Your settings in the inventory section will be changed",
  },
  advertiser: "advertiser",
  reportUrl: "Statistic URL",
  manager: "manager",
  publisher: "publisher",
  table: {
    noRowsToShow: "No rows available",
  },

  serverError: {
    campaigns: {
      loadCampaignsFailed: "Load campaigns failed. Server error occurs.",
    },
    Notification: {
      readNotificationFailed: "Couldn't mark as read. Server error occurs.",
    },
  },
  
};